# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Shared helpers for capa feature snapshot fixtures.

Used by `tests/test_feature_snapshots.py`. The snapshots live under
`tests/fixtures/snapshots/features/`; each entry in `manifest.json`
identifies a sample in the `tests/data/` submodule plus the corresponding
`.frz` file. Fixtures are regenerated by hand via::

    python -m capa.features.freeze --reproducible SAMPLE OUTPUT

and the manifest is edited by hand. The `--reproducible` flag zeros out
dynamic header metadata (e.g. capa version) so fixtures stay stable across
capa version bumps.
"""

from __future__ import annotations

from typing import Optional
from pathlib import Path

from pydantic import BaseModel, ConfigDict

TESTS_DIR = Path(__file__).resolve().parent
TESTS_DATA_DIR = TESTS_DIR / "data"
FEATURE_SNAPSHOTS_DIR = TESTS_DIR / "fixtures" / "snapshots" / "features"
MANIFEST_PATH = FEATURE_SNAPSHOTS_DIR / "manifest.json"


class FeatureSnapshot(BaseModel):
    """One entry in the feature snapshot manifest."""

    model_config = ConfigDict(frozen=True)

    name: str
    sample: str
    freeze: str
    explanation: str = ""
    # Git commit at which this fixture was last regenerated. Purely informational:
    # on test failure we surface it so a reviewer can run `git log <commit>..HEAD`
    # to see what's changed since. Not validated — humans keep it accurate.
    generated_at_commit: Optional[str] = None
    format: Optional[str] = None
    backend: Optional[str] = None
    os: Optional[str] = None

    @property
    def sample_path(self) -> Path:
        return TESTS_DATA_DIR / self.sample

    @property
    def freeze_path(self) -> Path:
        return FEATURE_SNAPSHOTS_DIR / self.freeze


class Manifest(BaseModel):
    version: int = 1
    description: str = ""
    snapshots: list[FeatureSnapshot]

    @classmethod
    def from_file(cls, path: Path = MANIFEST_PATH) -> "Manifest":
        return cls.model_validate_json(path.read_text(encoding="utf-8"))
