#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
generate-freeze-snapshots

Generate (or regenerate) the capa freeze snapshot fixtures under
`tests/fixtures/freezes/`. Reads the snapshot list from `manifest.json`,
produces a `.frz` file per entry by running feature extraction against the
corresponding sample in `tests/data/`, and rewrites the manifest with the
current capa version, HEAD commit, and freeze sha256.

Usage::

    python scripts/generate-freeze-snapshots.py             # regenerate all
    python scripts/generate-freeze-snapshots.py --only NAME # only given names
    python scripts/generate-freeze-snapshots.py --check     # verify without writing
"""

from __future__ import annotations

import sys
import logging
import argparse
import subprocess
from pathlib import Path

import capa.version

# Allow running as a script from the repo root.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tests.snapshot_util import (  # noqa: E402
    FREEZES_DIR,
    Manifest,
    Snapshot,
    generate_freeze_bytes,
    sha256_hex,
)

logger = logging.getLogger("generate-freeze-snapshots")


def git_head_commit() -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"
    return out.decode("ascii").strip()


def regenerate(snapshot: Snapshot, commit: str, *, check: bool) -> Snapshot:
    if not snapshot.sample_path.exists():
        raise FileNotFoundError(
            f"sample missing: {snapshot.sample_path} "
            "(did you forget `git submodule update --init tests/data`?)"
        )

    data = generate_freeze_bytes(
        snapshot.sample_path,
        format=snapshot.format,
        backend=snapshot.backend,
        os=snapshot.os,
    )
    digest = sha256_hex(data)

    if check:
        if not snapshot.freeze_path.exists():
            raise AssertionError(f"freeze missing: {snapshot.freeze_path}")
        existing = snapshot.freeze_path.read_bytes()
        if existing != data:
            raise AssertionError(
                f"freeze drift for {snapshot.name}: regenerated bytes differ from "
                f"{snapshot.freeze_path}"
            )
        logger.info("ok   %-24s  sha256=%s", snapshot.name, digest)
    else:
        snapshot.freeze_path.parent.mkdir(parents=True, exist_ok=True)
        snapshot.freeze_path.write_bytes(data)
        logger.info(
            "wrote %-24s  sha256=%s  (%d bytes)", snapshot.name, digest, len(data)
        )

    return Snapshot(
        name=snapshot.name,
        sample=snapshot.sample,
        freeze=snapshot.freeze,
        format=snapshot.format,
        backend=snapshot.backend,
        os=snapshot.os,
        capa_version=capa.version.__version__,
        generated_at_commit=commit,
        sha256=digest,
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--only", nargs="+", help="regenerate only the snapshots with these names"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that on-disk snapshots match regeneration; do not write anything",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="enable debug logging"
    )
    args = parser.parse_args(args=argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(message)s",
    )

    manifest = Manifest.load()
    commit = git_head_commit()
    if args.only:
        wanted = set(args.only)
        missing = wanted - {s.name for s in manifest.snapshots}
        if missing:
            parser.error(f"no such snapshot(s): {sorted(missing)}")
    else:
        wanted = None

    new_entries: list[Snapshot] = []
    failures = 0
    for snapshot in manifest.snapshots:
        if wanted is not None and snapshot.name not in wanted:
            new_entries.append(snapshot)
            continue
        try:
            new_entries.append(regenerate(snapshot, commit, check=args.check))
        except Exception as e:
            failures += 1
            logger.error("fail %-24s  %s", snapshot.name, e)

    if not args.check:
        Manifest(
            version=manifest.version,
            description=manifest.description,
            snapshots=new_entries,
        ).save()
        logger.info("manifest updated: %s", FREEZES_DIR / "manifest.json")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
